adamw:
  learning_rate: 0.0002
  adam_b1: 0.8
  adam_b2: 0.99
  lr_decay: 0.999

hifigan:
  resblock: 1
  upsample_rates: [10, 8, 2, 2]
  upsample_kernel_sizes: [20, 16, 4, 4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  hop_size: 320

  hubert_dim: 1024
  hifi_dim: 512

mel:
  num_mels: 80
  num_freq: 1025
  n_fft: 1024
  win_size: 1024

  fmin: 0
  fmax: 8000
  fmax_for_loss: null

# data config
audio_ext: flac
batch_size: 32
num_workers: 0
sample_rate: 16000
segment_size: 7040
train_file: ls-test-clean_prematch.tar
valid_file: ls-test-clean_prematch.tar

# train config
seed: 0
checkpoint_dir: logs
training_epochs: 5
stdout_interval: 1
checkpoint_interval: 2
summary_interval: 1
validation_interval: 2
fp16: true
